### ISSUE TITLE
Venmo API Key

### ISSUE THREAD

**Issue by iloveitaly** [evanpurkhiser/venmo-auto-cashout#1]
What's the easiest way to get a venmo API key? Do you need to register an application and go through the oauth flow or can you generate a personal API key somewhere?

**Comment by evanpurkhiser** [comment]
No, there's no public venmo API so you just have to use the API client to authenticate with your username and password.

I've updated the readme with notes on how to use do it :-)

**Comment by iloveitaly** [comment]
Thanks for the notes! That's exactly what I was looking for.
